name: "test-scheduler"

on:
  workflow_dispatch:


  schedule:
    - cron:  '*/30 5 * * *'    # triggers the workflow every day at 5:30 UTC

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

jobs:
  continuous-tests:
    name: Run Test cases
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout                      # action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install dependencies
        run: |
         go get -u "github.com/gruntwork-io/terratest/modules/random"
         go get -u "github.com/gruntwork-io/terratest/modules/terraform"

      -
        name: setup terraform
        uses: hashicorp/setup-terraform@v1  # sets up Terraform CLI in your GitHub Actions workflow
        with:
          terraform_version: 0.13.1

      - name: Run Test
        working-directory: test
        run: go test -v -timeout 250m ./...
        env:
          IC_API_KEY: ${{ secrets.ACCESS_KEY }}
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
